version: '3'
services:
  rabbit:
    image: rabbitmq:3-management
    ports:
    - "5672:5672"
    - "15672:15672"
    networks:
    - hutch
    restart: always
  flower:
    image: gmauro/flower
    ports:
    - "5555:5555"
    networks:
    - hutch
    restart: always
    command: ["flower", "--port=5555", "--broker=amqp://guest:guest@rabbit:5672//", "--broker_api=http://guest:guest@rabbit:15672/api/"]

networks:
  hutch:
